import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-inter`}
      >
        <div className="flex min-h-screen bg-gray-50">
          {/* Sidebar */}
          <aside className="w-64 bg-white border-r border-gray-200 flex flex-col">
            {/* Logo */}
            <div className="p-6 border-b border-gray-200">
              <div className="text-2xl font-bold text-gray-900">ZIGGY BENT</div>
            </div>

            {/* Navigation Links */}
            <nav className="flex-1 p-4">
              <ul className="space-y-2">
                <li>
                  <a href="/" className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md">
                    ZIGGY BENT
                  </a>
                </li>
                <li>
                  <a href="/garden" className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md">
                    Garden
                  </a>
                </li>
                <li>
                  <a href="/vanitas" className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md">
                    Vanitas
                  </a>
                </li>
                <li>
                  <a href="/resources" className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md">
                    Resources
                  </a>
                </li>
                <li>
                  <a href="/news" className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md">
                    News
                  </a>
                </li>
              </ul>
            </nav>

            {/* Social Icons */}
            <div className="p-4 border-t border-gray-200">
              <div className="flex gap-3 justify-center">
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="X">
                  𝕏
                </a>
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="YouTube">
                  ▶
                </a>
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="GitHub">
                  ⚡
                </a>
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="Instagram">
                  📷
                </a>
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="TikTok">
                  ♪
                </a>
                <a href="#" className="text-gray-600 hover:text-gray-900" aria-label="Discord">
                  💬
                </a>
              </div>
            </div>
          </aside>

          {/* Main Content Area */}
          <div className="flex-1 flex flex-col">
            {/* Top Bar */}
            <header className="bg-white border-b border-gray-200 px-8 py-4">
              <div className="flex justify-end">
                <button className="px-6 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800">
                  Sign up for ZIGGY BENT
                </button>
              </div>
            </header>

            {/* Page Content */}
            <main className="flex-1 p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
